### ISSUE TITLE
Crash on Death

### ISSUE THREAD

**Issue by marcos4503** [Sarinsa/Damp-Soil#2]
Hi! I've noticed that my game has been crashing if I die near a functioning Sprinkler block.

This is happening on Forge, 1.20.1, Forge version 47.2.0 with Java 17.0.2.

If I die near a Sprinkler block (i.e. a Sprinkler block is in a loaded Chunk, and spraying water), and then I click "Respawn" and respawn in a distant location where there are no other functioning Sprinkler blocks in any loaded Chunk, the game either freezes or simply crashes.

I think this is the exact Stack Trace...

**Comment by marcos4503** [comment]
[trace-resume.txt](https://github.com/user-attachments/files/16683508/trace-resume.txt)

**Comment by marcos4503** [comment]
This is the full log file...

**Comment by marcos4503** [comment]
[full-trace.log](https://github.com/user-attachments/files/16683566/full-trace.log)

**Comment by marcos4503** [comment]
I also noticed one more thing. After I respawn and the game crashes, if I teleport back to the location of the Sprinkler that caused the crash, it gives one last splash of water and stops until I trigger it again.

I'm a programmer, but I don't know much about Minecraft modding, but if I had to guess, I'd say there's a loop running that causes the splash of water, but when I respawn there's no longer the Sprinkler block, which causes the crash or freeze.

**Comment by Sarinsa** [comment]
interesting, Ill investigate this tomorrow. thanks for the report

**Comment by marcos4503** [comment]
Just to add: If I'm playing on a Forge server with the same mods installed with everything of the test scenario, and I repeat the steps, the Server doesn't crash, only my Client.

I did the test twice just to confirm, and indeed, the server continues to run normally.

**Comment by Sarinsa** [comment]
Okay, so the thing that is most likely happening here is that when the player is for any reason quickly moved away from a sprinkler, be it by death or teleportation, the chunk the sprinkler is in is unloaded before the client-side logic has finished running (spawning splash particles and whatnot). Deploying a fix shortly

**Comment by marcos4503** [comment]
I see! I'm glad it's fixed! I'll test the new update as soon as possible!

**Comment by Sarinsa** [comment]
Update is live on Modrinth now. If you find any other bonkers bugs feel free to post a new issue. Thanks again for your report!
